### PR TITLE
bump server version

### PR DESCRIPTION
**Pull request by lukasIO**

### CODE REVIEW

**Review by davidzhao — APPROVED** [review]
thanks for bumping this!

**Comment by davidzhao** [comment]
released to the helm repo.

**Comment by lukasIO** [comment]
thanks! does it work for you though?
I just tried and helm fetch answers with 
`Error: scheme "s3" not supported`
and helm upgrade gives me
`Error: failed to download "livekit/livekit-server"`

**Comment by davidzhao** [comment]
hmm, that's strange.. I'll investigate

**Comment by davidzhao** [comment]
ok, the last built had an issue.. rebuilt and it works for me now.

**Pull request merged**
