### PR TITLE
feat: no load balancer fallback to cluster ip

### PR DESCRIPTION
**Pull request by zifeo**

### CODE REVIEW

**Comment by davidzhao** [comment]
Can you describe why this is needed? Which Kubernetes engine requires cluster IP?

**Comment by zifeo** [comment]
@davidzhao I am using RKE2 k8s distribution with ingress-nginx to:
- [expose](https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/) tcp and single udp port
- get tls on web socket with cert-manager

The current nodeport service is not needed for this setup and can cause some troubles on small cluster deployment. I am currently adding a custom service to manage my use case, however I believe this use case may be worth supporting upstream.

**Comment by davidzhao** [comment]
> @davidzhao I am using RKE2 k8s distribution with ingress-nginx to:
> 
> * [expose](https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/) tcp and single udp port
> * get tls on web socket with cert-manager
> 
> The current nodeport service is not needed for this setup and can cause some troubles on small cluster deployment. I am currently adding a custom service to manage my use case, however I believe this use case may be worth supporting upstream.

The default Service type is already `ClusterIP` ([kube docs](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types)). isn't your change asking for the same behavior?

**Comment by zifeo** [comment]
@davidzhao Good catch! And I saw that missed most of the patches I wanted to submit. I roll-back to default and added the missing elements.

**Comment by zifeo** [comment]
@davidzhao Can you please review again?

**Comment by davidzhao** [comment]
I'm traveling this week, will review when I get back on Sunday.

**Comment by zifeo** [comment]
@davidzhao You are hopefully back now :) ?

**Comment by davidzhao** [comment]
My bad, dropped the ball on this. will have a look this week!

**Comment by davidzhao** [comment]
looks like the PR has been changed to enable usage without host networking and instead rely on single-port udp mode?

We do not recommend using single port UDP in production, as it has bottlenecks wrt performance. Also, enabling service port mapping does not seem to be related to the type of load balancer one wants to specify to me. Could you explain the motivation for that?

**Comment by zifeo** [comment]
@davidzhao I know it is not advised, but this setup is the only that can work when there is no load balancer available within the cluster (e.g. only a single one, locked with an ingress). Therefore I believe that you should also support this option, especially for small deployment that do not require a perfect performance.

**Review by davidzhao — APPROVED** [review]
That makes sense to me. Sorry for the delays in getting this merged.

**Pull request merged**
