### PR TITLE
commented resources section to be reference only

### PR DESCRIPTION
**Pull request by ahmed-adly-khalil**
the current resources in the sample are unrealistically high, I was able to run a test cluster smoothly with much lower specs

### CODE REVIEW

**Comment by davidzhao** [comment]
thanks for the PR @ahmed-adly-khalil! If you could take a moment to sign the CLA, we'll get this merged right away!

**Comment by ahmed-adly-khalil** [comment]
@davidzhao sure, what's the link?

**Comment by davidzhao** [comment]
> Contributor License Agreement

here it is: https://cla-assistant.io/livekit/livekit-helm?pullRequest=20

**Comment by ahmed-adly-khalil** [comment]
> > Contributor License Agreement
> 
> here it is: https://cla-assistant.io/livekit/livekit-helm?pullRequest=20

done

**Pull request merged**
